site_name: hotdog-werx/codeguide
site_description: A guide to coding practices and standards for hotdog-werx
site_url: https://hotdog-werx.github.io/codeguide/
repo_url: https://github.com/hotdog-werx/codeguide
repo_name: hotdog-werx/codeguide

nav:
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Guides:
      - Python Projects: guides/python.md

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: lucide/moon-star
        name: Switch to light mode
  # favicon: assets/zensical.png
  # logo: assets/zensical.svg
  icon:
    tag:
      default: lucide/hash

# Plugins
plugins:
  - search
  - tags

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - zensical.extensions.preview:
      targets:
        include:
          - customization.md
          - setup/extensions/*
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: zensical
      repo: zensical
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hotdog-werx
