[settings]
experimental = true
python.uv_venv_auto = true

[env]
GITHUB_REPO_OWNER = "{{ cookiecutter.owner }}"
GITHUB_REPO_NAME = "{% raw %}{{ config_root | basename }}{% endraw %}"
GITHUB_REPO = "{% raw %}{{ env.GITHUB_REPO_OWNER }}/{{ env.GITHUB_REPO_NAME }}{% endraw %}"
GIT_CLIFF_CONFIG = "./.pkglink/.codeguide/configs/cliff.toml"

[tasks]
pkglink.run = "uvx pkglink sync"

[hooks]
postinstall = ["mise run pkglink", "poe setup"]

[tools]
uv = "0.7.20"
dprint = "0.50.1"
starship = "1.21.1"
git-cliff = "2.11.0"

"pipx:poethepoet" = "0.36.0"
"pipx:pkglink" = "1.0.1"
"pipx:tbelt" = "0.0.3"
"pipx:ruff" = "0.12.3"
"pipx:hotdog-werx/releez" = "topic/changelog-regen"
