[tool.coverage.html]
directory = ".coverage-files/htmlcov"

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if __name__ == .__main__.:",
  "if typing.TYPE_CHECKING:",
  "\\.\\.\\.",
]
show_missing = true
