name: deploy-docs

on:
  push:
    branches: [master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11
          activate-environment: true
      - name: mise
        uses: jdx/mise-action@v2
      - name: poe
        run: uv tool install poethepoet
      - name: dependencies
        run: uvx --from poethepoet poe uv-sync
      - name: check-python
        run: poe check-python
      - name: build-docs
        run: poe build-docs
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
